services:
  server:
    volumes:
      - type: volume
        source: fe-volume
        target: /var/www/frontend/assets
      - type: volume
        source: admin-volume
        target: /var/www/admin/assets
      - certbot-volume-www:/var/website/certbot:ro
      - certbot-volume-config:/etc/nginx/ssl:ro
  frontend:
    volumes:
      - fe-volume:/cdg/public
  admin:
    volumes:
      - admin-volume:/admin
  certbot:
    image: certbot/certbot
    command: certonly --webroot -w /var/www/certbot -d cdgroup-ae.com -d cdgroup-ae.com -d admin.cdgroup-ae.com -m colin@tinybird.ca --agree-tos
    volumes:
      - certbot-volume-config:/var/www/certbot:rw
      - certbot-volume-www:/etc/letsencrypt:rw
volumes:
  fe-volume:
  admin-volume:
  certbot-volume-www:
    external: true
  certbot-volume-config:
    external: true
