services:
  server:
    depends_on:
      - certbot
    volumes:
      - type: volume
        source: fe-volume
        target: /var/www/frontend/assets
      - type: volume
        source: admin-volume
        target: /var/www/admin/assets
      - type: volume
        source: certbot-www-volume
        target: /var/website/certbot:ro
      - type: volume
        source: certbot-config-volume
        target: /etc/nginx/ssl:ro
  frontend:
    volumes:
      - fe-volume:/cdg/public
  admin:
    volumes:
      - admin-volume:/admin
  certbot:
    image: certbot/certbot
    command: certonly --webroot -w /var/www/certbot -d cdgroup-ae.com -d cdgroup-ae.com -d admin.cdgroup-ae.com -m colin@tinybird.ca --agree-tos
    volumes:
      - certbot-config-volume:/var/www/certbot:rw
      - certbot-www-volume:/etc/letsencrypt:rw
volumes:
  fe-volume:
  admin-volume:
  certbot-www-volume:
    external: true
  certbot-config-volume:
    external: true
