services:
  server:
    build: ./server
    networks:
      default:
        aliases:
          - ${ADMIN_URL}
    ports:
      - 80:80
    command: [nginx, '-g', 'daemon off;']
    depends_on:
      - admin
      - frontend
  frontend:
    build:
      context: ./frontend
      args:
        DEV: ${DEV}
        MIX_ADMIN_URL: ${ADMIN_URL_PROTOCOL}${ADMIN_URL}
    command: sh -c "php-fpm7; if [ ${DEV} = "true" ] ; then npm run watch; else tail -f /dev/null; fi"
    environment:
      ADMIN_URL: ${ADMIN_URL_PROTOCOL}${ADMIN_URL}
      MIX_ADMIN_URL: ${ADMIN_URL_PROTOCOL}${ADMIN_URL}
      RECAPTCHA_SITE_KEY: ${RECAPTCHA_SITE_KEY}
      RECAPTCHA_SECRET_KEY: ${RECAPTCHA_SECRET_KEY}
      MAIL_DRIVER: ${MAIL_DRIVER}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_ENCRYPTION: ${MAIL_ENCRYPTION}
      SESSION_DRIVER: ${SESSION_DRIVER}
      BROADCAST_DRIVER: ${BROADCAST_DRIVER}
      CACHE_DRIVER: ${CACHE_DRIVER}
      LOG_CHANNEL: ${LOG_CHANNEL}
      DEV: ${DEV}
      APP_DEBUG: ${DEV}
      MAIL_FROM_NAME: "CDG Website"
  admin:
    build: 
      context: ./admin
      args:
        DEV: ${DEV}
    command: sh -c "php-fpm7; tail -f /dev/null;"
    depends_on:
      db:
        condition: service_healthy
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USER}
  db:
    image: mysql:5.7
    environment:
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_ROOT_HOST: '%'
    ports:
      - 3306:3306
    healthcheck:
      test: mysqladmin ping -h localhost -u root -p${DB_ROOT_PASSWORD}
    volumes:
      - db-volume:/var/lib/mysql:rw
volumes:
  db-volume:
    external: true