services:
  server:
    volumes:
      - type: volume
        source: fe-volume
        target: /var/www/frontend/assets
        read_only: true
      - type: volume
        source: admin-volume
        target: /var/www/admin/assets
        read_only: true
      - type: bind
        source: /var/website/certs/www
        target: /var/website/certbot
        read_only: true
      - type: bind
        source: /var/website/certs/config
        target: /etc/nginx/ssl
        read_only: true
  frontend:
    volumes:
      - fe-volume:/cdg/public
  admin:
    volumes:
      - admin-volume:/admin
  certbot:
    image: certbot/certbot
    depends_on:
      - server
    volumes:
      - type: bind
        source: /var/website/certs/www
        target: /var/www/certbot
      - type: bind
        source: /var/website/certs/config
        target: /etc/letsencrypt
volumes:
  fe-volume:
  admin-volume:
