name: Deploy
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Copy Files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          source: "./*"
          target: "/var/website/tmp"
      - name: Build everything
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            cd /var/website;
            rm -rf www;
            mv tmp www;
            cd www;
            sed -i 's#DB_PASSWORD=#DB_PASSWORD=${{secrets.PROD_DB_PASS}}#g' .env.example;
            sed -i 's#DB_NAME=#DB_NAME=${{secrets.PROD_DB_NAME}}#g' .env.example;
            sed -i 's#DB_USER=#DB_USER=${{secrets.PROD_DB_USER}}#g' .env.example;
            sed -i 's#DB_ROOT_PASSWORD=#DB_ROOT_PASSWORD=${{secrets.PROD_DB_ROOT_PASSWORD}}#g' .env.example;
            sed -i 's#RECAPTCHA_SITE_KEY=#RECAPTCHA_SITE_KEY=${{secrets.RECAPTCHA_SITE_KEY}}#g' .env.example;
            sed -i 's#RECAPTCHA_SECRET_KEY=#RECAPTCHA_SECRET_KEY=${{secrets.RECAPTCHA_SECRET_KEY}}#g' .env.example;
            sed -i 's#MAIL_PASSWORD=#MAIL_PASSWORD=${{secrets.MAIL_PASSWORD}}#g' .env.example;
            sed -i 's#ADMIN_HOST=#ADMIN_HOST=admin.cdgroup-ae.com#g' .env.example;
            sed -i 's#FRONTEND_HOST=#ADMIN_HOST=cdgroup-ae.com#g' .env.example;
            
            mv .env.example .env;
            ./buildProd.sh;
            docker compose down -v;
            ./runProd.sh;